baseURL = "http://jamphan.dev"
languageCode = "en-us"
title = "jamphan.dev"
theme = "cactus"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[params]

  colortheme = "white" # dark, light, white, or classic
  mainSection = "posts"
  tagsOverview = true
  description = "Hi there! My name is Jamie. I'm a software engineer that likes to learn about development and computing in general. I spend too much time researching about an assortment of random topics I find interesting and I've decided to post them on the internet to share with you. I hope you find it interesting :)"

  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/jamie-kt-phan/"
  [[params.social]]
    name = "email"
    link = "spam@jamphan.dev"  # no need for "mailto:" in the head